[package]
name = "windows-theme"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
windows = { version = "0.59.0", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_System_Registry",
  "Storage_Streams",
  "System_UserProfile",
] }
